algoritmo "idade"
// Função :
// Autor :
// Data : 18/05/2023
// Seção de Declarações 
var
idade: inteiro
nome: caracter

inicio

//entrada

escreval("digite o seu nome: ")
leia (nome)

escreval("digite a sua idade: ")
leia (idade)

//processamento

se (idade >= 18 )entao
 escreval(nome, " ja pode ser preso, cuidado")

senao
 escreval(nome, " você é novinho(a) demais")
 
fimse

fimalgoritmo
