algoritmo "semnome"
// Função :
// Autor :
// Data : 25/05/2023
// Seção de Declarações 
var
temp: real

inicio

escreval("Qual a temperatura da sua cidade? ")
leia(temp)

se (temp <20)entao
  escreval ("O clima na sua cidade esta frio!")
senao
  se (temp <25 )entao
   escreval ("O clima na sua cidade esta normal!")
  senao
   escreval ("O clima na sua cidade esta quente!")
  fimse
fimse
 


// Seção de Comandos 
fimalgoritmo
